name: floor_chiper
description: >
  The typesafe, reactive and lightweight SQLite abstraction for your Flutter applications.
  This is an example on how to use the library.
version: 0.17.0
homepage: https://github.com/vitusortner/floor
author:
  - vitusortner
  - Dreamwalker

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  floor:
    path: ../floor/
  path: any
  path_provider: any
  permission_handler: any
  floor_annotation:
    path: ../floor_annotation/

  meta: ^1.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  collection: ^1.16.0
  mockito: ^5.1.0
  matcher: ^0.12.11
  build_runner: ^2.1.8

  floor_generator:
    path: ../floor_generator/


dependency_overrides:
  sqflite:
    git:
      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
      path: sqflite
      ref: fmdb_override