name: floor_chiper
description: >
  The typesafe, reactive and lightweight SQLite abstraction for your Flutter applications.
  This is an example on how to use the library.
version: 0.18.0
homepage: https://github.com/JAICHANGPARK/floor_chiper
author:
  - vitusortner
  - Dreamwalker

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  floor:
    path: ../floor/
  path: any
  path_provider: any
  permission_handler: any


  meta: ^1.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  collection: ^1.14.13
  mockito: ^4.1.1
  matcher: ^0.12.9
  build_runner: ^1.10.3

  floor_generator:
    path: ../floor_generator/


dependency_overrides:
  sqflite:
    git:
      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
      path: sqflite
      ref: fmdb_override