name: example
description: >
  The typesafe, reactive and lightweight SQLite abstraction for your Flutter applications.
  This is an example on how to use the library.
version: 1.1.0
homepage: https://floor.codes
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:

  flutter:
    sdk: flutter

  floor:
    path: ../floor/

  path_provider: any
  permission_handler: any
  path: any

dev_dependencies:
  build_runner: ^2.1.1
  floor_generator:
    path: ../floor_generator/
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true