name: floor
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the runtime dependency.
version: 1.1.0
homepage: https://floor.codes
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  floor_annotation:
    git:
      url: https://github.com/vitusortner/floor.git
      path: floor_annotation
      ref: develop
  flutter:
    sdk: flutter
  meta: ^1.7.0
  path: ^1.8.0
  sqflite_sqlcipher: ^2.0.0
  sqflite_common_ffi: ^2.0.0+3

dev_dependencies:
  build_runner: ^2.1.1
  collection: ^1.15.0
  floor_generator:
    git:
      url: https://github.com/JAICHANGPARK/floor_chiper.git
      path: floor_generator
      ref: feature/1.1.0
  flutter_test:
    sdk: flutter
  matcher: ^0.12.11
  mockito: ^5.0.15
