name: floor
description: >
  The typesafe, reactive and lightweight SQLite abstraction for your Flutter applications.
  This library is the runtime dependency.
version: 1.1.1
homepage: https://github.com/vitusortner/floor
author: Vitus Ortner <vitusortner.dev@gmail.com>

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  path: ^1.8.1
#  sqflite: ^1.3.1+1
#  sqflite_common_ffi: ^1.1.1
  sqflite_sqlcipher: ^2.1.0
  floor_annotation:
    path: ../floor_annotation/

  meta: ^1.7.0
  flutter:
    sdk: flutter

dev_dependencies:
  collection: ^1.16.0
  mockito: ^5.1.0

  flutter_test:
    sdk: flutter
  floor_generator:
    path: ../floor_generator/

  build_runner: ^2.1.8
  matcher: ^0.12.11
