name: floor
description: >
  The typesafe, reactive, and lightweight SQLite abstraction for your Flutter applications.
  This library is the runtime dependency.
version: 1.0.0
homepage: https://github.com/vitusortner/floor
author: Vitus Ortner <vitusortner.dev@gmail.com>
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  floor_annotation:
    git:
      url: https://github.com/vitusortner/floor.git
      path: floor_annotation
      ref: develop
  meta: ^1.3.0
  path: ^1.8.0
#  sqflite: ^2.0.0+2
  sqflite_sqlcipher: ^2.0.0-nullsafety.0
  sqflite_common_ffi: ^2.0.0

dev_dependencies:
  build_runner: ^1.11.5
  collection: ^1.15.0
  floor_generator:
    git:
      url: https://github.com/JAICHANGPARK/floor_chiper.git
      path: floor_generator
      ref: feature/1.0.0
  flutter_test:
    sdk: flutter
  matcher: ^0.12.10
  mockito: ^5.0.0
