# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    # implicit-dynamic: false

linter:
  rules:
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    test_types_in_equals: true
    unrelated_type_equality_checks: true
    valid_regexps: true
    annotate_overrides: true
    hash_and_equals: true
    prefer_is_not_empty: true
    avoid_empty_else: true
    cancel_subscriptions: true
    close_sinks: true
    always_declare_return_types: true
    camel_case_types: true
    empty_constructor_bodies: true
    avoid_init_to_null: true
    constant_identifier_names: true
    one_member_abstracts: true
    slash_for_doc_comments: true
    sort_constructors_first: true
    unnecessary_brace_in_string_interps: true

    # === doc rules ===
    public_member_api_docs: true

    # ignore specify types
    always_specify_types: false
    # ignore const for now
    prefer_const_constructors: false