name: sqflite_sqlcipher
homepage: https://github.com/davidmartos96/sqflite_sqlcipher
description: Flutter plugin for SQLite, a self-contained, high-reliability,
  embedded, SQL database engine. (SqlCipher support)
version: 1.1.1

environment:
  sdk: '>=2.6.0 <3.0.0'
  flutter: ">=1.10.1 <2.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.davidmartos96.sqflite_sqlcipher
        pluginClass: SqfliteSqlCipherPlugin
      ios:
        pluginClass: SqfliteSqlCipherPlugin
      macos:
        pluginClass: SqfliteSqlCipherPlugin


dependencies:
  flutter:
    sdk: flutter
  synchronized: '>=2.0.2 <4.0.0'
  path: '>=1.5.1 <3.0.0'
  sqflite_common: ^1.0.1

dev_dependencies:
  pedantic: '>=1.4.0 <3.0.0'
  process_run: '>=0.10.7'
  http: '>=0.12.0+2'
  flutter_test:
    sdk: flutter
  test_api:
